import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
  // --- Luxury Yachts Co — Instagram Reels ---
  {
    id: "luxury-yachts-reel-1",
    video_title: "Luxury Yachts Co — Instagram Reel #1",
    video_description:
      "Stunning Instagram Reel showcasing a luxury yacht walkthrough with cinematic drone shots, smooth transitions, and aspirational lifestyle editing.",
    tags: ["Instagram Reels", "Yacht", "Luxury", "Cinematic"],
    cover_image: "/projects/luxury-yachts-reel-1.png",
    publish_date: "2025-05-01",
    client_name: "Luxury Yachts Co",
    client_image: "/companies/luxury-yachts-co.png",
    client_feedback: "",
    video_link: "https://www.instagram.com/reel/DNRcsMQzh0W/",
    project_images: [],
    category: ["Reels"],
    duration: "0:30",
    software_used: ["Adobe Premiere Pro", "After Effects"],
    role: "Lead Editor & Motion Designer",
  },
  {
    id: "luxury-yachts-reel-2",
    video_title: "Luxury Yachts Co — Instagram Reel #2",
    video_description:
      "Dynamic Instagram Reel featuring a premium yacht on open waters with sleek motion graphics, color grading, and engaging vertical format editing.",
    tags: ["Instagram Reels", "Yacht", "Luxury", "Vertical Video"],
    cover_image: "/projects/luxury-yachts-reel-2.png",
    publish_date: "2025-05-15",
    client_name: "Luxury Yachts Co",
    client_image: "/companies/luxury-yachts-co.png",
    client_feedback: "",
    video_link: "https://www.instagram.com/reel/DNhHxleT-A5/",
    project_images: [],
    category: ["Reels"],
    duration: "0:30",
    software_used: ["Adobe Premiere Pro", "After Effects"],
    role: "Lead Editor & Motion Designer",
  },
  {
    id: "luxury-yachts-reel-3",
    video_title: "Luxury Yachts Co — Instagram Reel #3",
    video_description:
      "Scroll-stopping Instagram Reel for Luxury Yachts Co, showcasing yacht interiors with premium color grading and trending audio-synced editing.",
    tags: ["Instagram Reels", "Yacht", "Interior", "Short-form"],
    cover_image: "/projects/luxury-yachts-reel-3.png",
    publish_date: "2025-06-01",
    client_name: "Luxury Yachts Co",
    client_image: "/companies/luxury-yachts-co.png",
    client_feedback: "",
    video_link: "https://www.instagram.com/reel/DOJSu2zFbrT/",
    project_images: [],
    category: ["Reels"],
    duration: "0:35",
    software_used: ["Adobe Premiere Pro"],
    role: "Lead Editor",
  },
  {
    id: "luxury-yachts-reel-4",
    video_title: "Luxury Yachts Co — Instagram Reel #4",
    video_description:
      "High-impact Instagram Reel featuring yacht lifestyle content — sunset cruising, deck views, and premium brand positioning for social media.",
    tags: ["Instagram Reels", "Yacht", "Lifestyle", "Sunset"],
    cover_image: "/projects/luxury-yachts-reel-4-clean.png",
    publish_date: "2025-06-20",
    client_name: "Luxury Yachts Co",
    client_image: "/companies/luxury-yachts-co.png",
    client_feedback: "",
    video_link: "https://www.instagram.com/reel/DO2MFewjK05/",
    project_images: [],
    category: ["Reels"],
    duration: "0:40",
    software_used: ["Adobe Premiere Pro", "After Effects"],
    role: "Lead Editor & Motion Designer",
  },
  {
    id: "luxury-yachts-reel-5",
    video_title: "Luxury Yachts Co — Instagram Reel #5",
    video_description:
      "Cinematic Instagram Reel capturing yacht detail shots — polished chrome, sleek hulls, and luxury finishes — with premium post-production.",
    tags: ["Instagram Reels", "Yacht", "Detail Shots", "Premium"],
    cover_image: "/projects/luxury-yachts-reel-5-clean.png",
    publish_date: "2025-06-25",
    client_name: "Luxury Yachts Co",
    client_image: "/companies/luxury-yachts-co.png",
    client_feedback: "",
    video_link: "https://www.instagram.com/reel/DO9zxGJE_3g/",
    project_images: [],
    category: ["Reels"],
    duration: "0:20",
    software_used: ["Adobe Premiere Pro"],
    role: "Lead Editor",
  },
  {
    id: "luxury-yachts-reel-6",
    video_title: "Luxury Yachts Co — Instagram Reel #6",
    video_description:
      "Engaging Instagram Reel with fast-paced yacht tour editing, dynamic transitions, and optimized for maximum Instagram engagement and reach.",
    tags: ["Instagram Reels", "Yacht Tour", "Dynamic Edits", "Social Media"],
    cover_image: "/projects/luxury-yachts-reel-6-clean.png",
    publish_date: "2025-07-05",
    client_name: "Luxury Yachts Co",
    client_image: "/companies/luxury-yachts-co.png",
    client_feedback: "",
    video_link: "https://www.instagram.com/reel/DPKjTl5k9Z6/",
    project_images: [],
    category: ["Reels"],
    duration: "0:30",
    software_used: ["Adobe Premiere Pro", "After Effects"],
    role: "Lead Editor & Motion Designer",
  },
  {
    id: "luxury-yachts-reel-7",
    video_title: "Luxury Yachts Co — Instagram Reel #7",
    video_description:
      "Professional Instagram Reel for a luxury yacht listing, featuring aerial and interior shots with polished transitions and brand-consistent styling.",
    tags: ["Instagram Reels", "Yacht", "Listing Video", "Aerial"],
    cover_image: "/projects/luxury-yachts-reel-7-clean.png",
    publish_date: "2025-07-20",
    client_name: "Luxury Yachts Co",
    client_image: "/companies/luxury-yachts-co.png",
    client_feedback: "",
    video_link: "https://www.instagram.com/reel/DQH1tNKEywJ/",
    project_images: [],
    category: ["Reels"],
    duration: "0:30",
    software_used: ["Adobe Premiere Pro"],
    role: "Lead Editor",
  },
  {
    id: "luxury-yachts-reel-8",
    video_title: "Luxury Yachts Co — Instagram Reel #8",
    video_description:
      "Vertical-format Instagram Reel showcasing yacht on-water experience with immersive POV shots, stabilized footage, and cinematic color grading.",
    tags: ["Instagram Reels", "Yacht", "POV", "Cinematic"],
    cover_image: "/projects/luxury-yachts-reel-8-clean.png",
    publish_date: "2025-08-01",
    client_name: "Luxury Yachts Co",
    client_image: "/companies/luxury-yachts-co.png",
    client_feedback: "",
    video_link: "https://www.instagram.com/reel/DQsiGI2DgxX/",
    project_images: [],
    category: ["Reels"],
    duration: "0:45",
    software_used: ["Adobe Premiere Pro", "After Effects"],
    role: "Lead Editor & Motion Designer",
  },
  {
    id: "luxury-yachts-reel-9",
    video_title: "Luxury Yachts Co — Instagram Reel #9",
    video_description:
      "Premium Instagram Reel for Luxury Yachts Co, combining lifestyle footage with smooth motion graphics and call-to-action overlays for lead generation.",
    tags: ["Instagram Reels", "Yacht", "Lead Gen", "CTA"],
    cover_image: "/projects/luxury-yachts-reel-9-clean.png",
    publish_date: "2025-08-15",
    client_name: "Luxury Yachts Co",
    client_image: "/companies/luxury-yachts-co.png",
    client_feedback: "",
    video_link: "https://www.instagram.com/reel/DRQlmHRk07Z/",
    project_images: [],
    category: ["Reels"],
    duration: "0:30",
    software_used: ["Adobe Premiere Pro"],
    role: "Lead Editor",
  },
  // --- Luxury Yachts Co — YouTube Videos ---
  {
    id: "luxury-yachts-cruisers-540",
    video_title: "Luxury Yachts Co — 2015 Cruisers Yacht 540 Sport Coupe",
    video_description:
      "Full walkthrough video of the 2015 Cruisers Yacht 540 Sport Coupe featuring interior and exterior tours, engine room details, and cinematic lifestyle shots for the Luxury Yachts Co YouTube channel.",
    tags: ["YouTube", "Yacht Tour", "Cruisers Yacht", "Luxury"],
    cover_image: "LBJ2YllJeRQ",
    publish_date: "2024-09-01",
    client_name: "Luxury Yachts Co",
    client_image: "/companies/luxury-yachts-co.png",
    client_feedback: "",
    video_link: "https://youtu.be/LBJ2YllJeRQ",
    project_images: [],
    category: ["YouTube"],
    duration: "5:00",
    software_used: ["Adobe Premiere Pro", "DaVinci Resolve"],
    role: "Editor & Colorist",
  },
  {
    id: "luxury-yachts-nx-280",
    video_title: "Luxury Yachts Co — NX Boats 280 Xtreme",
    video_description:
      "Dynamic showcase video of the NX Boats 280 Xtreme, featuring on-water performance footage, cockpit details, and lifestyle shots for the Luxury Yachts Co sales channel.",
    tags: ["YouTube", "Boat Tour", "NX Boats", "Performance"],
    cover_image: "ns8E0pvZmDs",
    publish_date: "2024-09-15",
    client_name: "Luxury Yachts Co",
    client_image: "/companies/luxury-yachts-co.png",
    client_feedback: "",
    video_link: "https://youtu.be/ns8E0pvZmDs",
    project_images: [],
    category: ["YouTube"],
    duration: "4:00",
    software_used: ["Adobe Premiere Pro"],
    role: "Lead Editor",
  },
  {
    id: "luxury-yachts-regal-3760",
    video_title: "Luxury Yachts Co — 2007 Regal 3760",
    video_description:
      "Comprehensive video tour of the 2007 Regal 3760, highlighting spacious interiors, helm station, and marina lifestyle shots for prospective buyers.",
    tags: ["YouTube", "Yacht Tour", "Regal", "Sales Video"],
    cover_image: "qWbgvWQu3H8",
    publish_date: "2024-10-01",
    client_name: "Luxury Yachts Co",
    client_image: "/companies/luxury-yachts-co.png",
    client_feedback: "",
    video_link: "https://youtu.be/qWbgvWQu3H8",
    project_images: [],
    category: ["YouTube"],
    duration: "5:00",
    software_used: ["Adobe Premiere Pro", "DaVinci Resolve"],
    role: "Editor & Colorist",
  },
  {
    id: "luxury-yachts-searay-540",
    video_title: "Luxury Yachts Co — 1999 Sea Ray 540 Sundancer",
    video_description:
      "Cinematic walkthrough of the classic 1999 Sea Ray 540 Sundancer, featuring drone aerials, cabin tour, flybridge views, and professional post-production.",
    tags: ["YouTube", "Yacht Tour", "Sea Ray", "Classic"],
    cover_image: "doCS6CBnz2I",
    publish_date: "2024-10-15",
    client_name: "Luxury Yachts Co",
    client_image: "/companies/luxury-yachts-co.png",
    client_feedback: "",
    video_link: "https://youtu.be/doCS6CBnz2I",
    project_images: [],
    category: ["YouTube"],
    duration: "6:00",
    software_used: ["Adobe Premiere Pro"],
    role: "Lead Editor",
  },
  {
    id: "luxury-yachts-cruisers-360",
    video_title: "Luxury Yachts Co — 2009 Cruisers Yachts 360 Express",
    video_description:
      "Professional showcase of the 2009 Cruisers Yachts 360 Express Cruiser with detailed interior walkthroughs, engine specs, and on-water performance clips.",
    tags: ["YouTube", "Yacht Tour", "Cruisers Yachts", "Express"],
    cover_image: "cqwF7auFd3Y",
    publish_date: "2024-11-01",
    client_name: "Luxury Yachts Co",
    client_image: "/companies/luxury-yachts-co.png",
    client_feedback: "",
    video_link: "https://youtu.be/cqwF7auFd3Y",
    project_images: [],
    category: ["YouTube"],
    duration: "5:30",
    software_used: ["Adobe Premiere Pro", "DaVinci Resolve"],
    role: "Editor & Colorist",
  },
  {
    id: "luxury-yachts-marquis-40",
    video_title: "Luxury Yachts Co — 2008 Marquis 40 SC",
    video_description:
      "Elegant video presentation of the 2008 Marquis 40 SC featuring salon tours, master stateroom details, and smooth cinematic transitions.",
    tags: ["YouTube", "Yacht Tour", "Marquis", "Luxury"],
    cover_image: "r-66Ky7acl4",
    publish_date: "2024-11-15",
    client_name: "Luxury Yachts Co",
    client_image: "/companies/luxury-yachts-co.png",
    client_feedback: "",
    video_link: "https://youtu.be/r-66Ky7acl4",
    project_images: [],
    category: ["YouTube"],
    duration: "4:30",
    software_used: ["Adobe Premiere Pro"],
    role: "Lead Editor",
  },
  {
    id: "luxury-yachts-bayliner-5788",
    video_title: "Luxury Yachts Co — 1998 Bayliner 5788 Pilot House",
    video_description:
      "In-depth video tour of the 1998 Bayliner 5788 Pilot House, showcasing the spacious pilothouse layout, multiple decks, and marina setting.",
    tags: ["YouTube", "Yacht Tour", "Bayliner", "Pilot House"],
    cover_image: "Gh8Nj-rm_5I",
    publish_date: "2024-12-01",
    client_name: "Luxury Yachts Co",
    client_image: "/companies/luxury-yachts-co.png",
    client_feedback: "",
    video_link: "https://youtu.be/Gh8Nj-rm_5I",
    project_images: [],
    category: ["YouTube"],
    duration: "5:00",
    software_used: ["Adobe Premiere Pro", "DaVinci Resolve"],
    role: "Editor & Colorist",
  },
  {
    id: "luxury-yachts-searay-480",
    video_title: "Luxury Yachts Co — 2000 Sea Ray 480 Sedan Bridge",
    video_description:
      "Complete video showcase of the 2000 Sea Ray 480 Sedan Bridge, highlighting the flybridge, salon, staterooms, and engine bay with professional editing.",
    tags: ["YouTube", "Yacht Tour", "Sea Ray", "Sedan Bridge"],
    cover_image: "399jrdtLYtg",
    publish_date: "2024-12-15",
    client_name: "Luxury Yachts Co",
    client_image: "/companies/luxury-yachts-co.png",
    client_feedback: "",
    video_link: "https://youtu.be/399jrdtLYtg",
    project_images: [],
    category: ["YouTube"],
    duration: "5:30",
    software_used: ["Adobe Premiere Pro"],
    role: "Lead Editor",
  },
  {
    id: "ichiban-reels",
    video_title: "Ichiban — Instagram Reels",
    video_description:
      "Dynamic Instagram reel for Ichiban, featuring eye-catching motion graphics, fast-paced editing, and scroll-stopping visual hooks designed for maximum social media engagement.",
    tags: ["Instagram Reels", "Motion Graphics", "Short-form", "Brand Content"],
    cover_image: "/projects/ichiban-thumb.jpg",
    publish_date: "2024-02-10",
    client_name: "Ichiban",
    client_image: "/companies/ichiban.png",
    client_feedback: "",
    video_link:
      "https://drive.google.com/file/d/11Nk88EMPYFHjxM4PZJwyXtc5ySmMusD1/view?usp=sharing",
    project_images: [],
    category: ["Reels", "Social Media Ads"],
    duration: "0:30",
    software_used: ["Adobe Premiere Pro", "After Effects"],
    role: "Editor & Motion Designer",
  },

  {
    id: "fam-estate-reels",
    video_title: "FAM Estate — Instagram Reels",
    video_description:
      "Stunning real estate reel for FAM Estate, featuring cinematic property shots, smooth transitions, and premium visual treatments to attract high-end buyers.",
    tags: ["Real Estate", "Instagram Reels", "Cinematic", "Property"],
    cover_image: "/projects/fam-estate-thumb.jpg",
    publish_date: "2024-03-05",
    client_name: "FAM Estate",
    client_image: "/companies/placeholder-client.png",
    client_feedback: "",
    video_link:
      "https://drive.google.com/file/d/1dBMDr8HFu0f5X5-rY_M0GXJVqJL5pPiM/view?usp=sharing",
    project_images: [],
    category: ["Reels", "Promo"],
    duration: "0:45",
    software_used: ["Adobe Premiere Pro", "DaVinci Resolve"],
    role: "Editor & Colorist",
  },
  {
    id: "qisaruma-reels",
    video_title: "Qisaruma — Instagram Reels",
    video_description:
      "Engaging Instagram reel crafted for Qisaruma, featuring vibrant visuals, trend-aligned editing techniques, and strategic pacing to maximize views and engagement.",
    tags: ["Instagram Reels", "Short-form", "Social Media", "Brand Content"],
    cover_image: "/projects/qisaruma-thumb.jpg",
    publish_date: "2024-02-28",
    client_name: "Qisaruma",
    client_image: "/companies/qisaruma.png",
    client_feedback: "",
    video_link:
      "https://drive.google.com/file/d/1aCll2ZSlWdj1c96BefEPD49LG4LSkJJo/view?usp=sharing",
    project_images: [],
    category: ["Reels", "Social Media Ads"],
    duration: "0:30",
    software_used: ["Adobe Premiere Pro"],
    role: "Lead Editor",
  },
  {
    id: "chef-elin-sulivan-ads",
    video_title: "Chef Elin Sulivan — Video Ads",
    video_description:
      "High-converting video advertisement for Chef Elin Sulivan, featuring appetizing food footage, engaging hooks, and platform-optimized editing for Facebook and Instagram ad campaigns.",
    tags: ["Video Ads", "Food Content", "Facebook Ads", "Instagram Ads"],
    cover_image: "/projects/chef-elin-thumb.jpg",
    publish_date: "2023-11-15",
    client_name: "Chef Elin Sulivan",
    client_image: "/companies/placeholder-client.png",
    client_feedback:
      "Incredible work! The ads drove real results for our brand.",
    video_link:
      "https://drive.google.com/file/d/1EJpws_fJVgE6q4adlU-fiIaczDRISBUh/view?usp=sharing",
    project_images: [],
    category: ["Social Media Ads", "Promo"],
    duration: "1:00",
    software_used: ["Adobe Premiere Pro", "After Effects"],
    role: "Editor & Motion Designer",
  },
  {
    id: "decluttr-promo-yt",
    video_title: "Decluttr — Promotional Video",
    video_description:
      "Cinematic promotional video for Decluttr, featuring clean storytelling, professional motion graphics, and polished post-production for YouTube and social media distribution.",
    tags: ["Promo Video", "YouTube", "Brand Story", "Motion Graphics"],
    cover_image: "UGAFIup5eGQ",
    publish_date: "2024-03-01",
    client_name: "Decluttr",
    client_image: "/companies/decluttr.png",
    client_feedback: "",
    video_link: "https://youtu.be/UGAFIup5eGQ",
    project_images: [],
    category: ["Promo", "YouTube"],
    duration: "1:30",
    software_used: ["Adobe Premiere Pro", "After Effects"],
    role: "Lead Editor & Motion Designer",
  },
  {
    id: "importir-org-clip",
    video_title: "Importir.org — Clip",
    video_description:
      "Engaging clip for Importir.org's YouTube channel, showcasing community highlights and success stories. Part of the content series that helped drive 125K+ views.",
    tags: ["YouTube", "Clip", "Community", "125K+ Views"],
    cover_image: "KcJyWVeZiQs",
    publish_date: "2021-10-15",
    client_name: "Importir.org",
    client_image: "/companies/importir-org.png",
    client_feedback: "",
    video_link: "https://youtu.be/KcJyWVeZiQs",
    project_images: [],
    category: ["YouTube"],
    duration: "3:00",
    software_used: ["Adobe Premiere Pro", "DaVinci Resolve"],
    role: "Editor & Colorist",
  },
  {
    id: "nft-co-promo",
    video_title: "NFT.co — Promotional Video",
    video_description:
      "Dynamic promotional video for NFT.co, blending futuristic motion graphics with sleek product demos to showcase the platform's Web3 marketplace.",
    tags: ["Promo", "Web3", "NFT", "Motion Graphics"],
    cover_image: "nHfx3_TpTZE",
    publish_date: "2022-06-20",
    client_name: "NFT.co",
    client_image: "/companies/nft-docial.png",
    client_feedback: "",
    video_link: "https://youtu.be/nHfx3_TpTZE",
    project_images: [],
    category: ["Promo"],
    duration: "1:00",
    software_used: ["After Effects", "Adobe Premiere Pro"],
    role: "Motion Designer",
  },
  {
    id: "importir-event-trailer",
    video_title: "Importir — Event Trailer",
    video_description:
      "High-energy event trailer for Importir's community gathering, edited as a YouTube Short with fast-paced cuts, dynamic transitions, and hype-building pacing.",
    tags: ["YouTube Shorts", "Event", "Trailer", "Short-form"],
    cover_image: "MbGQSDA_cy4",
    publish_date: "2022-01-10",
    client_name: "Importir.org",
    client_image: "/companies/importir-org.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/MbGQSDA_cy4",
    project_images: [],
    category: ["Reels", "Promo"],
    duration: "0:30",
    software_used: ["Adobe Premiere Pro"],
    role: "Lead Editor",
  },
  {
    id: "docial-promo",
    video_title: "Docial — Platform Promo",
    video_description:
      "Professional promotional video for Docial, a social platform, featuring clean UI animations, brand storytelling, and engaging visual effects to drive user sign-ups.",
    tags: ["Promo", "Tech Platform", "UI Animation", "Brand Video"],
    cover_image: "jlq1AUSh3pE",
    publish_date: "2023-02-14",
    client_name: "Docial",
    client_image: "/companies/nft-docial.png",
    client_feedback: "",
    video_link: "https://youtu.be/jlq1AUSh3pE",
    project_images: [],
    category: ["Promo"],
    duration: "1:00",
    software_used: ["After Effects", "Adobe Premiere Pro"],
    role: "Motion Designer",
  },
  {
    id: "intrapreneur-promo",
    video_title: "Intrapreneur — Promo Video",
    video_description:
      "Compelling promotional video for Intrapreneur, combining corporate storytelling with modern editing techniques to communicate the brand's mission and value proposition.",
    tags: ["Promo", "Corporate", "Brand Story", "Professional"],
    cover_image: "1QAEabKbjrg",
    publish_date: "2023-04-20",
    client_name: "Intrapreneur",
    client_image: "/companies/entrepreneurs-id.png",
    client_feedback: "",
    video_link: "https://youtu.be/1QAEabKbjrg",
    project_images: [],
    category: ["Promo", "YouTube"],
    duration: "1:30",
    software_used: ["Adobe Premiere Pro", "After Effects"],
    role: "Lead Editor & Motion Designer",
  },
  {
    id: "docial-10k-passes",
    video_title: "Docial — Free 10,000 Passes Campaign",
    video_description:
      "Viral campaign video for Docial's free 10,000 passes giveaway, designed with urgency-driven editing, countdown elements, and eye-catching motion graphics to maximize engagement.",
    tags: ["Campaign", "Giveaway", "Motion Graphics", "Social Media"],
    cover_image: "g3qrEA7QEes",
    publish_date: "2023-03-10",
    client_name: "Docial",
    client_image: "/companies/nft-docial.png",
    client_feedback: "",
    video_link: "https://youtu.be/g3qrEA7QEes",
    project_images: [],
    category: ["Social Media Ads", "Promo"],
    duration: "0:45",
    software_used: ["After Effects", "Adobe Premiere Pro"],
    role: "Motion Designer",
  },
];
